const express=require("express")
require('dotenv').config()
const app=express()
app.use(express.json())
const  department=require("./router/department")
const categories=require("./router/category")
const attribute=require("./router/attribute")
const product=require('./router/product')
const customer=require("./router/customer")
const order=require("./router/order")
const shoppingcart=require("./router/shoppingcart")
const tax=require("./router/tax")
const shipping=require("./router/shipping")
const custo=require("./router/cust")
app.use('/',department,categories,attribute,product,customer,order,shoppingcart,tax,shipping,custo)
app.listen(process.env.APP_PORT,()=>{
    console.log("listen port:",process.env.APP_PORT)
})